recipes:
    mac_os_x:
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: immacomputer
    homebrewalt:
        apps:
            - git-extras
            - hub
        cask_apps:
            - onepassword
            - dropbox
            - vagrant
            - sonos
            - iterm2
            - day-o
    authorization:
      sudo:
        users:
          - davedash
        passwordless: true

    dotfiles:
        vim:
            bundle:
    git:
      name: Dave Dash
      email: dd+github@davedash.com
